
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sehir
{

using System;
    using System.Collections.Generic;
    
public partial class HomeworkRequest
{

    public int S_ID { get; set; }

    public int H_ID { get; set; }

    public string title { get; set; }

    public string C_Code { get; set; }

    public System.DateTime ReqDate { get; set; }

    public string note { get; set; }



    public virtual HomeworkMaker HomeworkMaker { get; set; }

    public virtual User User { get; set; }

}

}
