//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehir
{
    using System;
    
    public partial class HomworkMaker1
    {
        public int ID { get; set; }
        public string H_Name { get; set; }
        public string H_Code { get; set; }
        public string descript { get; set; }
        public Nullable<int> Price { get; set; }
        public byte[] transcript { get; set; }
        public byte[] img { get; set; }
    }
}
