
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sehir
{

using System;
    using System.Collections.Generic;
    
public partial class Lecturer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Lecturer()
    {

        this.C_feedBack = new HashSet<C_feedBack>();

        this.CourseRequests = new HashSet<CourseRequest>();

    }


    public int ID { get; set; }

    public string C_Code { get; set; }

    public string descrip { get; set; }

    public byte[] img { get; set; }

    public Nullable<int> Price { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<C_feedBack> C_feedBack { get; set; }

    public virtual Course Course { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CourseRequest> CourseRequests { get; set; }

    public virtual User User { get; set; }

}

}
