//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehir
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SehirEntities : DbContext
    {
        public SehirEntities()
            : base("name=SehirEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_feedBack> C_feedBack { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<H_feedBack> H_feedBack { get; set; }
        public virtual DbSet<Homework> Homework { get; set; }
        public virtual DbSet<HomworkMaker> HomworkMakers { get; set; }
        public virtual DbSet<Lecturer> Lecturers { get; set; }
        public virtual DbSet<take> takes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<CoursesList_Result> CoursesList(Nullable<int> id, Nullable<bool> belongs)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var belongsParameter = belongs.HasValue ?
                new ObjectParameter("belongs", belongs) :
                new ObjectParameter("belongs", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CoursesList_Result>("CoursesList", idParameter, belongsParameter);
        }
    
        public virtual ObjectResult<HomworkMaker> HomeworkList(Nullable<int> id, Nullable<bool> belongs)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var belongsParameter = belongs.HasValue ?
                new ObjectParameter("belongs", belongs) :
                new ObjectParameter("belongs", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HomworkMaker>("HomeworkList", idParameter, belongsParameter);
        }
    
        public virtual ObjectResult<HomworkMaker> HomeworkList(Nullable<int> id, Nullable<bool> belongs, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var belongsParameter = belongs.HasValue ?
                new ObjectParameter("belongs", belongs) :
                new ObjectParameter("belongs", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HomworkMaker>("HomeworkList", mergeOption, idParameter, belongsParameter);
        }
    
        public virtual ObjectResult<UserCourseInfo_Result> UserCourseInfo(Nullable<int> id, string c_Code, string c_Name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var c_CodeParameter = c_Code != null ?
                new ObjectParameter("C_Code", c_Code) :
                new ObjectParameter("C_Code", typeof(string));
    
            var c_NameParameter = c_Name != null ?
                new ObjectParameter("C_Name", c_Name) :
                new ObjectParameter("C_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserCourseInfo_Result>("UserCourseInfo", idParameter, c_CodeParameter, c_NameParameter);
        }
    
        public virtual ObjectResult<CustomFeedback_Result> CustomFeedback(Nullable<int> t_id, string code, string name)
        {
            var t_idParameter = t_id.HasValue ?
                new ObjectParameter("T_id", t_id) :
                new ObjectParameter("T_id", typeof(int));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomFeedback_Result>("CustomFeedback", t_idParameter, codeParameter, nameParameter);
        }
    }
}
